#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#define SUCCESS 0
#define USER_EXIT 1
#define UNKNOWN_ERROR 2
#define ERROR_FILE_NOT_FOUND 3
#define ERROR_PERMISSION_DENIED 4
#define ERROR_MEMORY_ALLOCATION 5
#define ERROR_COPY_FAILED 6
#define ERROR_INVALID_ARGUMENT 7
#define ERROR_SAME_SOURCE 8
#define ERROR_CWD 9
#define ERROR_RESOLVING_PATH 10
#define ERROR_BUFFER_TOO_SMALL 11
#define ERROR_USER_NOT_FOUND 12
#define ERROR_EXECUTING_COMMAND 13
#define ERROR_PATH_INVALID 14
#define ERROR_PATH_TOO_LONG 15
#define ERROR_COMMAND_NOT_FOUND 256

#endif
