#ifndef ERROR_CODES_H
#define ERROR_CODES_H

enum error_codes {
    SUCCESS = 0,
    USER_EXIT,
    UNKNOWN_ERROR,
    ERROR_FILE_NOT_FOUND,
    ERROR_PERMISSION_DENIED,
    ERROR_MEMORY_ALLOCATION,
    ERROR_COPY_FAILED,
    ERROR_INVALID_ARGUMENT,
    ERROR_SAME_SOURCE,
    ERROR_CWD,
    ERROR_RESOLVING_PATH,
    ERROR_BUFFER_TOO_SMALL,
    ERROR_USER_NOT_FOUND,
    ERROR_EXECUTING_COMMAND,
    ERROR_PATH_INVALID,
    ERROR_PATH_TOO_LONG,
    ERROR_INVALID_SOURCE,
    ERROR_COMMAND_NOT_FOUND = 256
};

int printError(int error_code, const char *context);

#endif
