#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#define SUCCESS 0
#define ERROR_FILE_NOT_FOUND 1
#define ERROR_PERMISSION_DENIED 2
#define ERROR_MEMORY_ALLOCATION 3
#define ERROR_COPY_FAILED 4
#define ERROR_INVALID_ARGUMENT 5
#define ERROR_SAME_SOURCE 6
#define ERROR_CWD 7
#define ERROR_RESOLVING_PATH 8
#define ERROR_BUFFER_TOO_SMALL 9
#define ERROR_USER_NOT_FOUND 10

#endif
